//export const BASE_URL = 'http://localhost:3333'
export const BASE_URL_DATA = 'https://test-deploy-node-v2.herokuapp.com'
//export const BASE_URL = 'https://stm-auth-service.herokuapp.com'
export const BASE_URL_API_LOCAL = 'http://localhost:8080'
export const BASE_URL = 'https://stm-auth-service-v2.herokuapp.com'